version: "3.7"

# adjust models memory as needed
services:
  spawner:
    build:
      dockerfile: Dockerfile
      context: ./spawner
    command: ${MODE}
    volumes:
      - ~/Documents/NIST/3DPoseEvaluator/spawner/:/root/spawner
      - ~/Documents/NIST/3DPoseEvaluator/models/:/root/models

  init-device:
    build:
      dockerfile: Dockerfile
      context: ./
    command: docker-compose.pipeline.yml ${DEVICE}
    depends_on:
      spawner:
        condition: service_completed_successfully
    volumes:
      - ~/Documents/NIST/3DPoseEvaluator/:/root
