version: "3.7"
services:
  tool-base:
    build:
      dockerfile: Dockerfile
      context: ./src
    volumes:
      - host-vol:/home
  gast-net:
    build:
      dockerfile: Dockerfile
      context: ./models/gast-net
      shm_mem: '5gb'
    volumes:
      - shared-vol:/home
  vibe:
    build:
      dockerfile: Dockerfile
      context: ./models/vibe
      shm_mem: '5gb'
    volumes:
      - shared-vol:/home
  blazepose:
    build:
      dockerfile: Dockerfile
      context: ./models/blazepose
      shm_mem: '5gb'
    volumes:
      - shared-vol:/home

volumes:
  shared-vol:
  host-vol: 
    driver: local
    driver_opts:
      type: none
      device: ~/Documents/NIST/3DPoseEvaluator
      o: bind
