version: "3.7"
services:
  tool-base:
    build:
      dockerfile: Dockerfile
      context: ./src
    volumes:
      - test-vol:/home
  gast-net:
    build:
      dockerfile: Dockerfile
      context: ./models/gast-net
    volumes:
      - test-vol:/home
  vibe:
    build:
      dockerfile: Dockerfile
      context: ./models/vibe
    volumes:
      - test-vol:/home
  blazepose:
    build:
      dockerfile: Dockerfile
      context: ./models/blazepose
    volumes:
      - test-vol:/home

volumes:
  test-vol: 
    driver: local
    driver_opts:
      type: none
      device: ~/Documents/NIST/3DPoseEvaluator
      o: bind
