version: "3.7"

# adjust shared memory as needed
services:
  tool-base:
    build:
      dockerfile: Dockerfile
      context: ./src
    volumes:
      - host-vol:/home
  gast-net:
    build:
      dockerfile: Dockerfile
      context: ./models/gast-net
      shm_size: '5gb'
    volumes:
      - shared-vol:/home
  vibe:
    build:
      dockerfile: Dockerfile
      context: ./models/vibe
      shm_size: '5gb'
    volumes:
      - shared-vol:/home
  blazepose:
    build:
      dockerfile: Dockerfile
      context: ./models/blazepose
      shm_size: '5gb'
    volumes:
      - shared-vol:/home

volumes:
  shared-vol:
  host-vol:
    driver: local
    driver_opts:
      type: none
      device: ~/Documents/NIST/3DPoseEvaluator # set project directory absolute path here
      o: bind
