version: '3.7'
services:
  blazepose:
    build:
      context: ./models/blazepose
      dockerfile: Dockerfile
    shm_size: 1gb
    volumes:
    - video-vol:/root/video
    - data-vol:/root/tmp
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
  gast-net:
    build:
      context: ./models/gast-net
      dockerfile: Dockerfile
    shm_size: 10gb
    volumes:
    - video-vol:/root/video
    - data-vol:/root/tmp
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
  vibe:
    build:
      context: ./models/vibe
      dockerfile: Dockerfile
    shm_size: 10gb
    volumes:
    - video-vol:/root/video
    - data-vol:/root/tmp
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
volumes:
  data-vol: null
  host-vol:
    driver: local
    driver_opts:
      device: ~/Documents/NIST/3DPoseEvaluator
      o: bind
      type: none
  video-vol:
    driver: local
    driver_opts:
      device: ~/Documents/NIST/3DPoseEvaluator/videos/
      o: bind
      type: none
  models-vol:
    driver: local
    driver_opts:
      device: ~/Documents/NIST/3DPoseEvaluator/models/
      o: bind
      type: none
