dir: vibe
name: VIBE
output-dir: output
python-version: 3.7.0
cmd: python3 demo.py

# model flags
flags: 
  - "--vid_file" : "/root/video/sit_stand_x3-MATLAB_test.mp4"
  - "--output_folder": "output/"
  - "--tracker_batch_size": 1
  - "--vibe_batch_size": 64

# video pose overlay flags
animate-opt: 
  enable: ""
  disable: "--no_render"

# filetype extensions for data/video files
filetypes:
  data: "pkl"
  video: "mp4"

# pre-cmd-execution actions
actions:
  - "bash set_device.sh"
  