dir: gast-net
name: GAST-Net-3DPoseEstimation
output-dir: output
python-version: 3.6.5
cmd: python3 gen_skes.py

# model flags
flags: 
  - "-v" : "sit_stand_x3-MATLAB_test.mp4"
  - "-np" : 1

# video pose overlay flags
animate-opt: 
  enable: "--animation"
  disable: ""

# filetype extensions for data/video files
filetypes:
  data: "npz"
  video: "mp4"

# pre-cmd-execution actions
actions: 
  - "bash set_device.sh"
  - "cp /root/video/sit_stand_x3-MATLAB_test.mp4 /root/GAST-Net-3DPoseEstimation/data/video"
    