dir: blazepose
name: Blazepose
output-dir: output
python-version: 3.8
cmd: python3 main.py


# model flags
flags:
  - "-v": "/root/videos/sit_stand_x3-MATLAB_test.mp4"

# video pose overlay flags
animate-opt: 
  enable: "--animate"
  disable: ""

# filetype extensions for data/video files
filetypes:
  data: "npz"
  video: "mp4"

# pre-cmd-execution actions
actions: ~
  